### ISSUE TITLE
Howcan I address this error:  Error in aperm.default(grid$Data, perm) :    'perm' is of wrong length 6 (!= 4)

### ISSUE THREAD

**Issue by catubela** [SantanderMetGroup/climate4R#12]
I'm trying to regrid Cordex data to the Eobs grid (As in your example 1 at: [https://github.com/SantanderMetGroup/climate4R/blob/master/notebooks/2018_climate4R_example1.Rmd]
I am only interested in the regridding and masking of the data (not bias correcting), so I am only pulling down a small amount of the eobs data:
```
`#Lat and Lon to maximise the area contained in the Cordex file`
```
```
lon <- c(-40.375, 64.4)
lat <- c(22.2,72.42)# 66.65)

eobs<-"http://opendap.knmi.nl/knmi/thredds/dodsC/e-obs_0.25regular/tx_0.25deg_reg_v17.0.nc"
#load the eobs data
Eobs.grid <- loadGridData(eobs, var = "tx",
                   season = 1:12,
                   years = 1971:1980,
                   lonLim = lon,
                   latLim = lat,
                   aggr.m = "sum",
                   condition = "GT",
                   threshold = 25)

makeAggregatedDataset(source.dir="C:/UsersDocuments/Climex/tasmax/",recursive = T, ncml.file = "test.ncml")
di <- dataInventory("test.ncml")
str(di$tasmax)

#---------------------------------CREATE THE DIC FILE-----------------------------------------------------------------
dictionary <- tempfile(pattern = "dicCDX", fileext = ".dic")
#Fill it with conversion factor for celcius. 
writeLines(c("identifier,short_name,time_step,lower_time_bound,upper_time_bound,cell_method,offset,scale,deaccum,derived,interface","tasmax,tasmax,24h,0,24,max,-273.15,1,0,0,"), dictionary)

#------------PULL DOWN THE DATA
test<-loadGridData("test.ncml","tasmax",dictionary = dictionary,lonLim = lon,latLim = lat)
#Get the grid from the Eobs data and apply it to the Cordex data
test <- interpGrid(test, getGrid(Eobs.grid))

#---------------Create monthly climatologies-----------------------------------
library(dplyr)

l <- lapply(1:12, function(i) {
  subsetGrid(test, season = i) %>% climatology()
})

mg <- do.call("makeMultiGrid", c(l, skip.temporal.check = TRUE))
mg$Data<-drop(mg$Data)

#Make the land mask
eobs.mask <- gridArithmetics(Eobs.grid, 0, operator = "*")
#Transpose the data
#eobs.mask$Data<-aperm(eobs.mask$Data)
#Apply the land mask
```
`masked_data <- gridArithmetics(mg, eobs.mask, operator = "+")`
```
```
Then I get the error:

Error in aperm.default(grid$Data, perm) : 
  'perm' is of wrong length 6 (!= 4)

When I look at the attributes of the 2 lists, I see that the dates are different:

![image](https://user-images.githubusercontent.com/70527978/99980552-458fc780-2da0-11eb-996c-efff3bcf8a36.png)

Versus:

![image](https://user-images.githubusercontent.com/70527978/99980624-58a29780-2da0-11eb-92d0-b785d3a0dc2c.png)

So I made the dates identical using: 
`eobs.mask$Dates<-mg$Dates`
But still I get the error. I also tried transposing the data within both the lists, but the error persists. Has this something to do with the dimensions? I saw there was an issue with this error elsewhere: https://github.com/SantanderMetGroup/downscaleR/issues/30 

```

**Comment by felipearandadelgado** [comment]
how do you solve it?
