### ISSUE TITLE
Difficulties in installing the package

### ISSUE THREAD

**Issue by mazanetti** [SantanderMetGroup/climate4R#5]
Kind developers, 
I'm experimenting some issues during the installation of the package climate4R.climdex. I followed the instructions in your readme but here it is the result: 

Error: Failed to install 'climate4R.climdex' from GitHub:
  (converted from warning) installation of package ‘C:/Users/MAZANE~1/AppData/Local/Temp/RtmpUrPQal/file2f806ead3cca/climate4R.climdex_0.2.1.tar.gz’ had non-zero exit status

Thank you.

**Comment by jbedia** [comment]
Hi, thanks for you ticket. Could you provide more specific information? Cheers

**Comment by mazanetti** [comment]
Fixed! Thank you for your reply. It was due to an old R version.

**Comment by vjjan91** [comment]
Hello,

I am still having rJava or other package related issues.
I have updated R, and even reinstalled Java, but I am unable to install the packages:

API rate limit exceeded for 106.51.141.21 is an error I am now getting...
