### ISSUE TITLE
problem with dependency "terra" for package "geoprocessoR"

### ISSUE THREAD

**Issue by miturbide** [SantanderMetGroup/climate4R#60]
Dependency  ‘terra >= 1.5.12' is required for package ‘geoprocessoR’. This is the error message:

Error: package or namespace load failed for ‘geoprocessoR’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘terra’ 1.4-22 is being loaded, but >= 1.5.12 is required

**Comment by zequihg50** [comment]
This is due to a python=3.7 dependency in the context of the hub, should not be a problem of the package.

**Comment by zequihg50** [comment]
Note however that downscaleR has several dependencies on python that need to be considered to be included in the package. See the [scripts](https://github.com/SantanderMetGroup/downscaleR/tree/devel/inst/py).
